{"uuid": "64bb365b-7947-46bb-8d8d-e41e83cfa82a", "children": ["6e21164b-4e0b-4f1d-a8d8-b19c02ddc56e"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line\n\n", "trace": "  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\GitHub\\JiHeeChoi.github.io\\Automation\\selenium_test_project\\conftest.py\", line 18, in driver\n    driver = DriverFactory.create_driver(browser)\n  File \"C:\\GitHub\\JiHeeChoi.github.io\\Automation\\selenium_test_project\\utilities\\driver_factory.py\", line 29, in create_driver\n    return webdriver.Firefox(\n           ~~~~~~~~~~~~~~~~~^\n        executable_path=GeckoDriverManager().install(),\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        options=firefox_options\n        ^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 180, in __init__\n    RemoteWebDriver.__init__(\n    ~~~~~~~~~~~~~~~~~~~~~~~~^\n        self,\n        ^^^^^\n        command_executor=executor,\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n        options=options,\n        ^^^^^^^^^^^^^^^^\n        keep_alive=True)\n        ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 266, in __init__\n    self.start_session(capabilities, browser_profile)\n    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 357, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 418, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1735549833284, "stop": 1735549836946}], "start": 1735549833284, "stop": 1735549836978}